### ISSUE TITLE
Track names no longer appearing

### ISSUE THREAD

**Issue by calebfergie** [fzakaria/HypeMachine-Extension#11]
Dear fzakaria,

My friends and I are very grateful for this extension. We've noticed recently the track names are no longer downloading - instead random letters and numbers appear. Is this a fixable problem?

Thank you

**Comment by luncht1me** [comment]
Hmmm...

The Master branch works except for the fact that the track names do not get saved..

Then when I update to this branch... the download button breaks, and I lose the ability to save favorites (the whole +'s disappear).

**Comment by anton-dileva** [comment]
Hey just got this, awesome thanks. 

The Master works fine but does not save track names unfortunately. 
The Chrome branch which is suppose to fix this, doesnt download tracks..Is this able to be fixed please? Im using chrome 46.0.2490.86

Cheers.

**Comment by fzakaria** [comment]
@anton-dileva  Its no longer ever possible to do it on account of Chrome. They've disabled the ability to set filename :(

**Comment by fzakaria** [comment]
Closing as this is unsolvable due to Chrome (from my undertsanding)

**Comment by naartjie** [comment]
What about populating the ID3 tags on the mp3 - I don't ever get those coming through. Is there a way to fix that? Is there another issue for that @fzakaria ?
