### ISSUE TITLE
Allow multiple downloads at once

### ISSUE THREAD

**Issue by ClimbsRocks** [fzakaria/HypeMachine-Extension#14]
I use this tool all the time to download songs I've favorited. It would be really nice to just be able to click a single button and be able to download all the songs on the page at once. 

I'm happy to submit a pull request for this later in the week!

Thanks again fro such an awesome extension!

**Comment by jhelmink** [comment]
I'd like to see that too! Good luck.

**Comment by robobeirne** [comment]
On the python version it seems possible to scrape all the songs so this should be doable shouldn't it be? Would be a massive help.

**Comment by fzakaria** [comment]
Closing this issue.
The latest code has this.
https://github.com/fzakaria/HypeMachine-Extension/pull/16
https://github.com/fzakaria/HypeMachine-Extension/commit/25377750365f5070386290cd8fec5ca890eac712
